In [5]:
import numpy as np
A = np.array([[1,2,3],[3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [6]:
array =np.zeros( (2,3) )
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
array =np.ones( (1,5) )
print(array)

[[1. 1. 1. 1. 1.]]


In [8]:
num_count = int(input("How many numbers will you enter: "))
numbers = []

for _ in range(num_count):
    num = int(input("Enter a number: "))
    numbers.append(num)

average = sum(numbers) / num_count
print("Average of the entered numbers:", round(average, 2))


Average of the entered numbers: 10.0
